global using Membership.Entities.Interfaces;
global using Membership.Entities.Interfaces.Login;
global using Membership.Entities.Interfaces.Login.RefreshToken;
global using Membership.Entities.Interfaces.Register;
global using Membership.Shared.Entities;
global using Membership.UserManager.Login;
global using Membership.UserManager.RefreshToken;
global using Membership.UserManager.Register;
global using Microsoft.Extensions.DependencyInjection;
